source 'https://rubygems.org'

gem 'rails', '3.2.13'

gem "mongoid", "~> 3.0.0"
gem 'bson_ext'

group :development do
	gem 'guard-livereload'
	gem 'better_errors'
	gem 'binding_of_caller'
end

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'angular-rails'
  gem 'angular-ui-rails'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

# Mapping
gem 'leaflet-rails'

gem 'jquery-rails'
gem 'simple_form'

# Keep passwords and API keys secure
gem "figaro", "= 0.6.3"

# User authorization & authentication
gem 'devise'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'omniauth-github'
gem 'omniauth-google-oauth2' 
gem 'cancan'

# Use thin as the app server
gem 'thin'

# Misc
gem 'awesome_print'
gem 'redcarpet'

